apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-angular-app.fullname" . }}
  labels:
    {{- include "my-angular-app.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007
  selector:
    {{- include "my-angular-app.selectorLabels" . | nindent 6 }}

